name: storyin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  http: ^1.2.0
  http_parser: ^4.0.2
  image_picker: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
